(function(){
  "use strict";
  const state={base:null,baseImage:null,subject:null,subjectImage:null,selected:null,textBlock:{x:0,y:0},textOffsets:{},graphicOffsets:{subject:{x:0,y:0},qr:{x:0,y:0},logo:{x:0,y:0}},values:{},positions:{title:{x:.50,y:.23,size:54,font:"Georgia",weight:"700",color:"#173f2b",align:"center"},subtitle:{x:.50,y:.29,size:34,font:"Georgia",weight:"500",color:"#173f2b",align:"center"},intro:{x:.50,y:.36,size:24,font:"Georgia",weight:"400",color:"#7a5a12",align:"center"},name:{x:.50,y:.45,size:64,font:"cursive",weight:"400",color:"#0a4229",align:"center"},description:{x:.50,y:.56,size:28,font:"Georgia",weight:"400",color:"#8a6510",align:"center"},course:{x:.50,y:.62,size:34,font:"Georgia",weight:"700",color:"#173f2b",align:"center"},date:{x:.22,y:.82,size:22,font:"Georgia",weight:"700",color:"#111",align:"center"},instructor:{x:.72,y:.82,size:28,font:"cursive",weight:"400",color:"#111",align:"center"}},graphics:{subject:{x:.23,y:.58,w:.34,h:.54},qr:{x:.89,y:.14,w:.08,h:.12},logo:{x:.50,y:.12,w:.16,h:.08}}};
  let canvas,ctx,status,drag=null;
  function el(id){return document.getElementById(id)}
  function todayIt(){return new Date().toLocaleDateString("it-IT",{day:"numeric",month:"long",year:"numeric"})}
  function readAsDataUrl(file){return new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.readAsDataURL(file)})}
  function loadImage(src){return new Promise(resolve=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>resolve(null);img.src=src})}
  function setStatus(t){if(status)status.textContent=t}
  async function loadBase(file){if(!file)return;state.base=await readAsDataUrl(file);state.baseImage=await loadImage(state.base);draw()}
  async function loadSubject(file){if(!file)return;state.subject=await readAsDataUrl(file);state.subjectImage=await loadImage(state.subject);state.selected={type:"graphic",id:"subject"};draw()}
  function collectValues(){document.querySelectorAll(".text-input").forEach(i=>state.values[i.dataset.text]=i.value);const s=el("courseSelect"),c=el("courseCustom");state.values.course=s.value==="ALTRO..."?c.value:s.value;state.values.date=el("dateText").value}
  function getTextPoint(id){const p=state.positions[id],off=state.textOffsets[id]||{x:0,y:0};return{x:p.x*canvas.width+state.textBlock.x+off.x,y:p.y*canvas.height+state.textBlock.y+off.y}}
  function drawText(id){const p=state.positions[id];if(!p)return;const text=state.values[id]||"",pt=getTextPoint(id);ctx.save();ctx.font=`${p.weight||400} ${p.size}px ${p.font}`;ctx.fillStyle=p.color;ctx.textAlign=p.align||"center";ctx.textBaseline="middle";ctx.fillText(text,pt.x,pt.y);ctx.restore()}
  function drawFrameFallback(){const g=ctx.createLinearGradient(0,0,canvas.width,canvas.height);g.addColorStop(0,"#f8f0d8");g.addColorStop(1,"#fff8e8");ctx.fillStyle=g;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle="#0b4b28";ctx.lineWidth=18;ctx.strokeRect(20,20,canvas.width-40,canvas.height-40);ctx.strokeStyle="#d5ad58";ctx.lineWidth=4;ctx.strokeRect(34,34,canvas.width-68,canvas.height-68)}
  function photoSettings(){return{removeLight:el("photoRemoveLight").checked,autoCutout:el("photoRemoveLight").checked,softEdges:el("photoSoftEdges").checked,shadow:el("photoShadow")?el("photoShadow").checked:true,feather:Number(el("photoFeather").value),opacity:Number(el("photoOpacity").value),scale:Number(el("photoScale").value),rotate:Number(el("photoRotate").value),cutTolerance:el("photoTolerance")?Number(el("photoTolerance").value):42}}
  function getGraphicBox(id){const g=state.graphics[id],off=state.graphicOffsets[id]||{x:0,y:0};return{x:g.x*canvas.width+off.x,y:g.y*canvas.height+off.y,w:g.w*canvas.width,h:g.h*canvas.height}}
  function drawSubject(){if(!state.subjectImage)return;const box=getGraphicBox("subject"),s=photoSettings();let sc=Math.min(box.w/state.subjectImage.width,box.h/state.subjectImage.height),w=state.subjectImage.width*sc*(s.scale/100),h=state.subjectImage.height*sc*(s.scale/100),x=box.x-w/2,y=box.y-h/2;const processed=window.K9Photo.processPhoto(state.subjectImage,w,h,s);ctx.save();ctx.globalAlpha=s.opacity/100;ctx.translate(x+w/2,y+h/2);ctx.rotate((s.rotate*Math.PI)/180);ctx.drawImage(processed,-processed.width/2,-processed.height/2,processed.width,processed.height);ctx.restore();if(state.selected&&state.selected.type==="graphic"&&state.selected.id==="subject")drawSelection(x,y,w,h)}
  function drawSelection(x,y,w,h){ctx.save();ctx.strokeStyle="#3aa7ff";ctx.lineWidth=4;ctx.setLineDash([12,8]);ctx.strokeRect(x,y,w,h);ctx.setLineDash([]);ctx.fillStyle="#3aa7ff";[[x,y],[x+w,y],[x,y+h],[x+w,y+h]].forEach(p=>ctx.fillRect(p[0]-8,p[1]-8,16,16));ctx.restore()}
  function drawQr(){const g=getGraphicBox("qr");ctx.save();ctx.fillStyle="#fff";ctx.fillRect(g.x,g.y,g.w,g.h);ctx.strokeStyle="#111";ctx.lineWidth=3;ctx.strokeRect(g.x,g.y,g.w,g.h);ctx.fillStyle="#111";ctx.font="18px monospace";ctx.textAlign="center";ctx.fillText("QR",g.x+g.w/2,g.y+g.h/2);ctx.restore()}
  function draw(){collectValues();ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);if(state.baseImage){if(canvas.width!==state.baseImage.width||canvas.height!==state.baseImage.height){canvas.width=state.baseImage.width;canvas.height=state.baseImage.height}ctx.drawImage(state.baseImage,0,0,canvas.width,canvas.height)}else{canvas.width=1600;canvas.height=1000;drawFrameFallback()}drawSubject();["title","subtitle","intro","name","description","course","date","instructor"].forEach(drawText);drawQr();setStatus("Anteprima aggiornata.")}
  function moveTextBlock(dir){const step=Number(el("textBlockStep").value);if(dir==="up")state.textBlock.y-=step;if(dir==="down")state.textBlock.y+=step;if(dir==="left")state.textBlock.x-=step;if(dir==="right")state.textBlock.x+=step;draw()}
  function moveSingleText(dir){const id=el("singleTextTarget").value,step=Number(el("singleTextStep").value);state.textOffsets[id]=state.textOffsets[id]||{x:0,y:0};if(dir==="up")state.textOffsets[id].y-=step;if(dir==="down")state.textOffsets[id].y+=step;if(dir==="left")state.textOffsets[id].x-=step;if(dir==="right")state.textOffsets[id].x+=step;state.selected={type:"text",id};draw()}
  function moveSingleGraphic(dir){const id=el("singleGraphicTarget").value,step=Number(el("singleGraphicStep").value);state.graphicOffsets[id]=state.graphicOffsets[id]||{x:0,y:0};if(dir==="up")state.graphicOffsets[id].y-=step;if(dir==="down")state.graphicOffsets[id].y+=step;if(dir==="left")state.graphicOffsets[id].x-=step;if(dir==="right")state.graphicOffsets[id].x+=step;state.selected={type:"graphic",id};draw()}
  function canvasPoint(e){const r=canvas.getBoundingClientRect(),t=e.touches?e.touches[0]:e;return{x:(t.clientX-r.left)*(canvas.width/r.width),y:(t.clientY-r.top)*(canvas.height/r.height)}}
  function pickObject(pt){const sb=getGraphicBox("subject");if(state.subjectImage&&pt.x>=sb.x-sb.w/2&&pt.x<=sb.x+sb.w/2&&pt.y>=sb.y-sb.h/2&&pt.y<=sb.y+sb.h/2)return{type:"graphic",id:"subject"};for(const id of ["title","subtitle","intro","name","description","course","date","instructor"]){const p=getTextPoint(id);if(Math.abs(pt.x-p.x)<260&&Math.abs(pt.y-p.y)<45)return{type:"text",id}}return null}
  function startDrag(e){const pt=canvasPoint(e),picked=pickObject(pt);if(!picked)return;state.selected=picked;drag={picked,start:pt};e.preventDefault();draw()}
  function moveDrag(e){if(!drag)return;const pt=canvasPoint(e),dx=pt.x-drag.start.x,dy=pt.y-drag.start.y;drag.start=pt;if(drag.picked.type==="graphic"){const id=drag.picked.id;state.graphicOffsets[id]=state.graphicOffsets[id]||{x:0,y:0};state.graphicOffsets[id].x+=dx;state.graphicOffsets[id].y+=dy;if(el("singleGraphicTarget"))el("singleGraphicTarget").value=id}else{const id=drag.picked.id;state.textOffsets[id]=state.textOffsets[id]||{x:0,y:0};state.textOffsets[id].x+=dx;state.textOffsets[id].y+=dy;if(el("singleTextTarget"))el("singleTextTarget").value=id}e.preventDefault();draw()}
  function stopDrag(){drag=null}
  function exportPng(){const a=document.createElement("a");a.href=canvas.toDataURL("image/png");a.download="certificato.png";a.click()}
  function exportPdf(){const w=window.open("");if(!w){alert("Consenti popup per esportare/stampare in PDF.");return}w.document.write(`<img src="${canvas.toDataURL("image/png")}" style="width:100%">`);w.document.close();w.print()}
  function bind(){el("baseFile").onchange=e=>loadBase(e.target.files[0]);el("subjectFile").onchange=e=>loadSubject(e.target.files[0]);document.querySelectorAll(".text-input").forEach(i=>i.addEventListener("input",draw));["photoRemoveLight","photoSoftEdges","photoFeather","photoOpacity","photoScale","photoRotate"].forEach(id=>el(id).addEventListener("input",draw));if(el("photoShadow"))el("photoShadow").addEventListener("input",draw);if(el("photoTolerance"))el("photoTolerance").addEventListener("input",draw);el("courseSelect").onchange=()=>{el("courseCustom").hidden=el("courseSelect").value!=="ALTRO...";draw()};el("courseCustom").oninput=draw;el("dateMode").onchange=()=>{const m=el("dateMode").value==="manual";el("dateManual").hidden=!m;if(!m){el("dateText").value=todayIt();draw()}};el("dateManual").onchange=()=>{if(el("dateManual").value){el("dateText").value=new Date(el("dateManual").value).toLocaleDateString("it-IT",{day:"numeric",month:"long",year:"numeric"});draw()}};document.querySelectorAll("[data-move-text-block]").forEach(b=>b.onclick=()=>moveTextBlock(b.dataset.moveTextBlock));document.querySelectorAll("[data-move-single-text]").forEach(b=>b.onclick=()=>moveSingleText(b.dataset.moveSingleText));document.querySelectorAll("[data-move-single-graphic]").forEach(b=>b.onclick=()=>moveSingleGraphic(b.dataset.moveSingleGraphic));el("resetTextBlock").onclick=()=>{state.textBlock={x:0,y:0};draw()};el("resetSingleText").onclick=()=>{delete state.textOffsets[el("singleTextTarget").value];draw()};el("resetSingleGraphic").onclick=()=>{state.graphicOffsets[el("singleGraphicTarget").value]={x:0,y:0};draw()};canvas.addEventListener("mousedown",startDrag);canvas.addEventListener("mousemove",moveDrag);window.addEventListener("mouseup",stopDrag);canvas.addEventListener("touchstart",startDrag,{passive:false});canvas.addEventListener("touchmove",moveDrag,{passive:false});canvas.addEventListener("touchend",stopDrag);el("exportPng").onclick=exportPng;el("exportPdf").onclick=exportPdf;el("clearAll").onclick=()=>{if(confirm("Reset completo?"))location.reload()};el("loadExample").onclick=()=>{state.baseImage=null;state.base=null;draw();setStatus("Esempio grafico generato.")};el("saveModel").onclick=()=>window.K9Archive.addModel({name:state.values.name||"Modello",state});el("saveIssued").onclick=()=>window.K9Archive.addIssued({name:state.values.name||"Certificato",values:state.values});el("backupJson").onclick=()=>window.K9Archive.backup();el("restoreJson").onclick=()=>el("restoreFile").click();el("restoreFile").onchange=e=>window.K9Archive.restore(e.target.files[0])}
  function init(){canvas=el("certificateCanvas");ctx=canvas.getContext("2d");status=el("status");el("dateText").value=todayIt();bind();draw()}
  window.K9Editor={init,state,draw};
})();
