/* K9 Template Studio - QR reale locale, versione 5-L byte mode */
(function(){
"use strict";
function gfTables(){let exp=new Array(512),log=new Array(256),x=1;for(let i=0;i<255;i++){exp[i]=x;log[x]=i;x<<=1;if(x&256)x^=0x11d}for(let i=255;i<512;i++)exp[i]=exp[i-255];return{exp,log}}
const GF=gfTables();
function gfMul(a,b){if(a===0||b===0)return 0;return GF.exp[GF.log[a]+GF.log[b]]}
function rsGen(deg){let poly=[1];for(let i=0;i<deg;i++){let next=new Array(poly.length+1).fill(0);for(let j=0;j<poly.length;j++){next[j]^=gfMul(poly[j],GF.exp[i]);next[j+1]^=poly[j]}poly=next}return poly}
function rsEcc(data,deg){let gen=rsGen(deg),res=new Array(deg).fill(0);for(const d of data){let factor=d^res.shift();res.push(0);if(factor){for(let i=0;i<deg;i++)res[i]^=gfMul(gen[i],factor)}}return res}
function utf8Bytes(s){return Array.from(new TextEncoder().encode(String(s)))}
function bitsPush(bits,val,len){for(let i=len-1;i>=0;i--)bits.push((val>>>i)&1)}
function makeCodewords(text){let bytes=utf8Bytes(text);if(bytes.length>106)bytes=bytes.slice(0,106);let bits=[];bitsPush(bits,4,4);bitsPush(bits,bytes.length,8);for(const b of bytes)bitsPush(bits,b,8);let cap=108*8;let term=Math.min(4,cap-bits.length);bitsPush(bits,0,term);while(bits.length%8)bits.push(0);let data=[];for(let i=0;i<bits.length;i+=8)data.push(parseInt(bits.slice(i,i+8).join(""),2));let pads=[0xec,0x11],pi=0;while(data.length<108)data.push(pads[pi++%2]);return data.concat(rsEcc(data,26))}
function set(m,r,x,y,v,res){if(x<0||y<0||x>=m.length||y>=m.length)return;m[y][x]=v;if(res)r[y][x]=true}
function finder(m,r,x,y){for(let dy=-1;dy<=7;dy++)for(let dx=-1;dx<=7;dx++){let xx=x+dx,yy=y+dy;if(xx<0||yy<0||xx>=m.length||yy>=m.length)continue;let on=(dx>=0&&dx<=6&&dy>=0&&dy<=6&&(dx===0||dx===6||dy===0||dy===6||(dx>=2&&dx<=4&&dy>=2&&dy<=4)));set(m,r,xx,yy,on,true)}}
function align(m,r,cx,cy){for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++){let ax=Math.abs(dx),ay=Math.abs(dy);set(m,r,cx+dx,cy+dy,(ax===2||ay===2||(dx===0&&dy===0)),true)}}
function formatBits(mask){let data=(1<<3)|mask;let v=data<<10,g=0x537;for(let i=14;i>=10;i--)if((v>>>i)&1)v^=g<<(i-10);return ((data<<10)|v)^0x5412}
function placeFormat(m,r,mask){let n=m.length,b=formatBits(mask);let c1=[[8,0],[8,1],[8,2],[8,3],[8,4],[8,5],[8,7],[8,8],[7,8],[5,8],[4,8],[3,8],[2,8],[1,8],[0,8]],c2=[[n-1,8],[n-2,8],[n-3,8],[n-4,8],[n-5,8],[n-6,8],[n-7,8],[8,n-8],[8,n-7],[8,n-6],[8,n-5],[8,n-4],[8,n-3],[8,n-2],[8,n-1]];for(let i=0;i<15;i++){let bit=((b>>>i)&1)===1;set(m,r,c1[i][0],c1[i][1],bit,true);set(m,r,c2[i][0],c2[i][1],bit,true)}}
function maskBit(mask,x,y){switch(mask){case 0:return((x+y)%2)===0;case 1:return(y%2)===0;case 2:return(x%3)===0;case 3:return((x+y)%3)===0;case 4:return((Math.floor(y/2)+Math.floor(x/3))%2)===0;case 5:return(((x*y)%2)+((x*y)%3))===0;case 6:return((((x*y)%2)+((x*y)%3))%2)===0;default:return((((x+y)%2)+((x*y)%3))%2)===0}}
function build(text,mask){let n=37,m=Array.from({length:n},()=>Array(n).fill(false)),r=Array.from({length:n},()=>Array(n).fill(false));finder(m,r,0,0);finder(m,r,n-7,0);finder(m,r,0,n-7);for(let i=8;i<n-8;i++){set(m,r,i,6,i%2===0,true);set(m,r,6,i,i%2===0,true)}align(m,r,30,30);set(m,r,8,n-8,true,true);placeFormat(m,r,mask);let cw=makeCodewords(text),bits=[];for(const b of cw)for(let i=7;i>=0;i--)bits.push((b>>>i)&1);let bit=0,up=true;for(let x=n-1;x>0;x-=2){if(x===6)x--;for(let yy=0;yy<n;yy++){let y=up?n-1-yy:yy;for(let dx=0;dx<2;dx++){let xx=x-dx;if(r[y][xx])continue;let v=(bits[bit++]||0)===1;if(maskBit(mask,xx,y))v=!v;m[y][xx]=v}}up=!up}return m}
function penalty(m){let n=m.length,p=0;for(let y=0;y<n;y++){let run=1,last=m[y][0];for(let x=1;x<n;x++){if(m[y][x]===last)run++;else{if(run>=5)p+=3+run-5;run=1;last=m[y][x]}}if(run>=5)p+=3+run-5}for(let x=0;x<n;x++){let run=1,last=m[0][x];for(let y=1;y<n;y++){if(m[y][x]===last)run++;else{if(run>=5)p+=3+run-5;run=1;last=m[y][x]}}if(run>=5)p+=3+run-5}return p}
function matrix(text){let best=null,bp=1e9;for(let mask=0;mask<8;mask++){let m=build(text,mask),p=penalty(m);if(p<bp){bp=p;best=m}}return best}
function toCanvas(canvas,text,opt,cb){try{let width=(opt&&opt.width)||300,margin=(opt&&opt.margin)||2,m=matrix(String(text||"")),n=m.length,cell=Math.floor(width/(n+margin*2)),size=cell*(n+margin*2);canvas.width=size;canvas.height=size;let ctx=canvas.getContext("2d");ctx.fillStyle="#fff";ctx.fillRect(0,0,size,size);ctx.fillStyle="#000";for(let y=0;y<n;y++)for(let x=0;x<n;x++)if(m[y][x])ctx.fillRect((x+margin)*cell,(y+margin)*cell,cell,cell);if(cb)cb(null)}catch(e){if(cb)cb(e)}}
window.QRCode={toCanvas};
})();